### ISSUE TITLE
JSON indentation

### ISSUE THREAD

**Issue by brunowego** [Knorcedger/generator-editorconfig#1]
What you think about set, by default, two spaces for json files?

**Comment by Knorcedger** [comment]
Hey,

I generally tried to follow Sindre Sorhus examples on the creation of the editorconfig file ([example](https://github.com/sindresorhus/ava/blob/0e6db13a918f0116927299271d91fff590328cb9/.editorconfig)). 

I also prefer tabs, but thought that people like spaces too :P And also use tabs for my json files. I could add it as a preference though, but the fact that package.json prefers spaces makes me wonder if all json files should be with spaces.

Not exactly sure on what path to go with..

**Comment by brunowego** [comment]
I understand, what you think if add a option for choice?

**Comment by Knorcedger** [comment]
What I'm trying to figure out is what that question would be and what it would do. What do you suggest?

**Comment by brunowego** [comment]
Good question, try anything like: What you prefer for indentation, 2 or 4 spaces? 

I'm not good with questions...

**Comment by Knorcedger** [comment]
I think I will add the following questions.

Do you prefer tabs or spaces?

If the user selects tab, no further questions will be asked, and the editorconfig that is currently been created will still be created.

If the user selects spaces, it will then ask for how many spaces do they prefer. And also apply spaces for all json files.

Does that sound better?

**Comment by brunowego** [comment]
Good!

**Comment by Knorcedger** [comment]
Took me quite some time (relocating to a new country is not easy), but hey, it's there!
